### ISSUE TITLE
Dashboard database schema

### ISSUE THREAD

**Issue by doug-leasure** [OxfordDemSci/UkraineNowPop#5]
Develop a draft database schema that will support the core functionality of the dashboard

**Comment by doug-leasure** [comment]
@GISRedeDev , here is a sketch for a preliminary database schema. Let me know if this makes sense or we need to discuss further. @edarin @alaparicioc , please let me know if you see issues with this, and we can revise as needed.

[WHO Ukraine Population.pdf](https://github.com/OxfordDemSci/UkraineNowPop/files/14268246/WHO.Ukraine.Population.pdf)

**Comment by doug-leasure** [comment]
Note: I committed a dataset with all pcodes globally to the `gisrede_api_frontend` branch [here](https://github.com/OxfordDemSci/UkraineNowPop/tree/gisrede_api_frontend/data/cod-ab). Let's put the entire contents of this spreadsheet into the "admin" table of the database. 

We will need to get the geometries from the country-specific COD-AB datasets, and we can add those to the database on a country-by-country basis rather than all at once.

**Comment by GISRedeDev** [comment]
Thanks for this @doug-leasure. At the moment we're kind of leaning towards wide format for the age/sex group populations, but not insistent on it if you prefer long format. Still trying to figure things out but we can speak about it soon.

**Comment by doug-leasure** [comment]
Thanks @GISRedeDev. I was thinking of long format to more easily accommodate a scenario where we cannot estimate population in 5-year age groups. The age_min and age_max columns in my proposed long format schema would allow for flexible age groupings whereas wide format would get complicated because new columns would be needed. 

We won't need to deviate from 5-year age groups for Ukraine, but we would need different age groups for Gaza.

**Comment by GISRedeDev** [comment]
Hi @doug-leasure 
When we were discussing the database some time ago, I vaguely remember that the pop datatypes would be int. Could you please confirm that, along with pop_upper and pop_lower? If they need to be floats/real, are you okay with them being returned by the api and shown in the dashboard as ints? If these still need to be floats, are you okay with use truncating them to 2 or 3 decimal places? Just thinking of the data load.
<img width="324" alt="image" src="https://github.com/OxfordDemSci/UkraineNowPop/assets/109098317/54a8dae7-8a19-4f06-a798-5ca524370b58">

**Comment by doug-leasure** [comment]
No problem to show them as ints in the dashboard, but probably best to plan for them to be reals in the database. 

Our model outputs will likely be integer, but I used reals in the schema so we are able to put the average of ints in the database if that ends up making the most sense (which is likely).

**Comment by GISRedeDev** [comment]
@doug-leasure I think this can be moved to done now if you're okay with it

**Comment by GISRedeDev** [comment]
@doug-leasure With reference to:
**_Note: I committed a dataset with all pcodes globally to the gisrede_api_frontend branch [here](https://github.com/OxfordDemSci/UkraineNowPop/tree/gisrede_api_frontend/data/cod-ab). Let's put the entire contents of this spreadsheet into the "admin" table of the database.

We will need to get the geometries from the country-specific COD-AB datasets, and we can add those to the database on a country-by-country basis rather than all at once._**

I can't remember how we agreed on languages, but I was thinking we said we'd allow up to 3 languages including English. I will add this csv as a table called `adm_metadata`. The only use I can see for it at the moment is to validate adm ids coming into the database from new countries, and then also later if you need the valid_from dates. Then for the `adm` table, i will make this schema:


![Image](https://github.com/OxfordDemSci/UkraineNowPop/assets/109098317/686484f5-a12a-4e05-8e4d-f16bd042e4cc)

With another table holding the additional languages for each country.  I think we can then keep the geometries at the finest level, and just aggregate them when returning them.

Let me know if you're against any of this. If you're fine to stick with English only, then I'm happy with that.

**Comment by doug-leasure** [comment]
@GISRedeDev, your plan for languages sounds good. 

I am not 100% sure that the COD-AB boundaries are always completely nested across levels. I know there are countries where the ADM-3 are slightly different than the ADM-2, but I do not know how the COD-AB have handled these situations. Are you worried that storing all three admin levels will be too heavy?

**Comment by GISRedeDev** [comment]
@doug-leasure I don't think it will be much heavier if we're holding all levels' geometries. I will change this to have 1 admin pcode column, with all levels in there, and then we can just select by admin_level. I will keep the 3 language fields as they are though.
