### ISSUE TITLE
Dummy data (i.e. expected model outputs)

### ISSUE THREAD

**Issue by doug-leasure** [OxfordDemSci/UkraineNowPop#6]
Provide some dummy data in the expected format for model outputs that @GISRede will read into the dashboard database. 

I expect that these data will be too big for GitHub so we probably want to have the script that generates them write into a subfolder of `./wd/`which should be included in the .gitignore. 

We will ultimately need to run the script that ingests these data into the database from the machine that is generating the model outputs.

**Comment by GISRedeDev** [comment]
@doug-leasure @alaparicioc I have just pushed (to gisrede_api_frontend) some distances matrices to `./data/dummy_tables` for euclidean distances from each Oblast to every other, and then also road distances for the same. The roads' topology is not in great shape so where network routes are broken, I have substituted the distance with the euclidean distance (you can find these where you find the corresponding euclidean distance is identical). We will fix this for the real outputs. Also, please note that the distances are calculated from the geometric centroid, rather than any other points that have yet to be decided on (population centroid etc.). Please let me know if there are any problems.

**Comment by GISRedeDev** [comment]
@doug-leasure @alaparicioc I forgot to mention that these files are in both csv and parquet format. As discussed, we will probably go ahead with parquet in future considering its compression. Please let us know if that causes any problems.

**Comment by doug-leasure** [comment]
@alaparicioc , do you have example model outputs to share at this point? I have also added @GISRedeDev to this issue because David is now putting together an example data format for the model outputs to be written into the dashboard database. Just want to keep those two efforts coordinated.

**Comment by GISRedeDev** [comment]
@doug-leasure @alaparicioc I have just pushed a branch [gisrede_issue6_dummy_pop_data ](https://github.com/OxfordDemSci/UkraineNowPop/tree/gisrede_issue6_dummy_pop_data)to try to make population and migration data for 1 month. It was taking hours to generate dummy data for migration as level 3, so I've only managed to do this for level 1.  Please let us know if it is sufficient for testing/development?

**Comment by alaparicioc** [comment]
Hi,

In the branch that @GISRedeDev created, I added a folder `UkraineNowPop/src/dashboard/api/scripts/data_simulation_R/`. This folder contains what I was working on, which corresponds to:

(1) A script that produces a dummy dataset that refers to subnational population estimates by 
      -	27 geographical units (oblasts) defined based on `src/dashboard/api/scripts/ADMIN_UNITS.csv`
      - 2 sex (female, male)
      - 17 five-year age groups (from 0 to 80+)
      - 740 days counting from 24 February 2022 until today (4 March 2024)

(2) The resulting csv file size obtained from the script described in (1). Its size is 66.455 MB. The dataset has 679,320 rows (27 oblasts x 2 sex  x  17 five-year age groups x 740 days counting from 24 February until 4 March 2024) and 10 columns. Columns correspond to admin1 codes (oblasts), sex, age groups, day/date, mean, median, upper and lower of 60% and 95% confidence intervals for population estimates. 

(3) A script that produces a dummy migration matrix that contains probabilities of moving between oblasts. Probabilities add to 1 per day. The resulting file size is around 1.11 GB. The output of this simulations produces a dataset of 17,662,320 rows (702 origin-destination pairs x 2 sex  x 17 five-year age groups x 740 days counting from 24 February 2022 until 4 March 2024) and 6 columns (orig, dest, sex, age_groups, day and probability of migration).

I would be more than happy to discuss any of the previous files with you.

**Comment by doug-leasure** [comment]
[like]  Douglas Leasure reacted to your message:
________________________________

**Comment by doug-leasure** [comment]
[like]  Douglas Leasure reacted to your message:
________________________________

**Comment by GISRedeDev** [comment]
Thank you very @alaparicioc. We will try to get these generated for this week.
@doug-leasure we will need to use the changes in [this ](https://github.com/OxfordDemSci/UkraineNowPop/tree/gisrede_issue6_dummy_pop_data) branch for further work today. Are you happy for us to branch from here, and then merge that into the main branch once this branch has been merged?

**Comment by alaparicioc** [comment]
Hi @GISRedeDev. I just wanted to let you know that I'm currently working on building on your code. I'll be making a few comments and amendments to the Python code, such as changing age_min + 5 to age_min + 4. Please bear with me as I'm not as familiar with Python as I'd like to be.

**Comment by alaparicioc** [comment]
I also updated the dummy data that you need for the dashboard based on the conversation I had with @Doug yesterday. 

The R code that produces the data is on Github, but also in the following shared folder. In the same folder, you can also find the csv files of the dummy data of subnational population estimates and migration matrix: https://drive.google.com/drive/folders/1qe6yR8-vNRE55CZtcCD5-kXIXFQvktaa?usp=sharing
 
In the specifics that @Doug had sketched, the population estimates (“dummy_data_pop.csv”) had a last variable named “pop_quantiles”. That column was changed to “pop_posterior”, in which you have a chain of 1000 values per row. This change enables summing arrays element-wise.

In the case of the migration matrix (“dummy_mig_matrix.csv”), it has now a column name “count”, which are the flows @GISRedeDev you were referring to circlize. 
Let me know if you have any question related to the dummy data.

**Comment by GISRedeDev** [comment]
Hi @alaparicioc and @doug-leasure  Thanks very much for this and I'm sorry it's taken a while to reply. 

Please don't worry about changing the python code. Just put what you would like changed in this issue, and I can change it. That code was written in quite a rush, so I don't know how readable it is. I will try to refactor everything this weekend. If you'd like to have call about the changes that you need, please feel free to set it up.

I haven't used your tables yet because I will need to adjust the database schema before doing so. We're hoping to give you a demo on Friday, after which I will sort out the database and insert your new data. Just 2 questions on the query:
1. Should the `pop_posterior` be sorted before summing element wise or are they in the order that you need;
2. Should the migration `count` column be summed between groups when multiple ages/sexes have been queried?

**Once again, please don't worry about changing my code. Just shout and I will do it**
Thanks!

**Comment by alaparicioc** [comment]
Ok. I will complete my comments between today and tomorrow morning.

One comment and for clarification, the dummy data in the google shared folder follows the schema (names and format of variables) sketched by @Doug in the images below: 
![image](https://github.com/OxfordDemSci/UkraineNowPop/assets/44085128/ecae9216-ceee-497a-8473-166ef8873e85)
![image](https://github.com/OxfordDemSci/UkraineNowPop/assets/44085128/1f2327d3-7218-45e2-8b34-1a7e8feee93a)

Now, you can find the answers of your questions below: 
1. Thanks for pinpointing this out. I have updated the dummy data for the subnational population estimates, and now the posteriors are organised as they need to be. So, no need to worry about this aspect.  
2. Yes, the "count" column can be summed when multiple ages/sexes have been queried.

**Comment by GISRedeDev** [comment]
Thank you @alaparicioc - I'm sorry, I was mistaken. Okay, I will try to upload this data to the database before our meeting on Friday. If not before then, then definitely over the weekend.

**Comment by GISRedeDev** [comment]
@alaparicioc Thank you for taking the time to go through our code and make suggestions. I will implement these this weekend, but I have a couple of simple clarifications that I will ask during the meeting again.
