### ISSUE TITLE
age-sex index

### ISSUE THREAD

**Issue by alaparicioc** [OxfordDemSci/UkraineNowPop#77]
Hi @edarin,

I’m trying to translate an age-sex model into the pipeline you created. However, when I attempt to create the index for age-sex using https://github.com/OxfordDemSci/UkraineNowPop/blob/f666404ca7cbaace5e669f251b9c0b9362482ff0/src/1_pop_data/10_create_master_index.R, the produced indexes do not seem to match the ages (see first image below), and each age index is produced twice for the same sex (see second image below). I might be doing something wrong. Could you check if you get the same results or if anything needs to be adjusted?

![image](https://github.com/user-attachments/assets/ab7714ca-6e8f-4136-a4f7-a645186bd4a5)

![image](https://github.com/user-attachments/assets/82372fe7-263f-402c-b308-fe0132aa84ff)

Thanks. 

Andrea Aparicio

**Comment by alaparicioc** [comment]
Hi,

I’ve made some changes to the code in my own working directory as follows:

agesex_index <- lapply(agesex, function(agesex_) agesex_col_to_query_args(agesex_) |> as_tibble()) |>
  bind_rows() |>
  mutate(
    a_name = str_sub(agesex, 3),
    a = as.integer(factor(paste0(age_min, age_max))),
    a_key = paste0(age_min, str_pad(age_max, 3, pad = "0")) |> as.integer(),
    s_name = str_sub(agesex, 1, 1),
    s = ifelse(s_name == "F", 2, 1),  # Assign 2 for F and 1 for M
    s_key = s
  ) |>
  select(-age_min, -age_max, -gender)


I haven’t committed anything just in case I’m wrong.

Note that I’ve changed s_key. In your code, it assigns 1 for F and 2 for M. The SocialMedia API uses 2 for F and 1 for M, so I adjusted it accordingly. This is because the plots I was producing were flipped, and I almost went mad trying to figure out what was going on.

Best regards,

Andrea Aparicio

**Comment by edarin** [comment]
Ey
You were right for the age indexing. It was an issue with the `agesex_col_to_query_args` code that is now being fixed with commit https://github.com/OxfordDemSci/UkraineNowPop/compare/dev...77-age-sex-index. 

```
agesex_index <- lapply(
  agesex, function(agesex_) {
    agesex_col_to_query_args(agesex_) |>
      as_tibble() |>
      mutate(agesex = agesex_)
  }
)
```

For the sex I am sorry I wasted your time. There is just one issue. Doug wanted to have an indexing that is flexible enough to have T, F and M and T,F,M depending of what is being requested. which means 1, 1-2, 1-2-3. Therefore `s = ifelse(s_name == "F", 2, 1)` wont work for indexing.  I have implemented [that](https://github.com/OxfordDemSci/UkraineNowPop/commit/dd18434dd8247a8c84361708897356668d29c32a):

```
 arrange(age_min, desc(agesex))|>
```
